//
//  HelpViewAnimation2.swift
//  AnimationSwiftUI
//
//  Created by Ainur on 27.03.2024.
//

import SwiftUI

struct HelpViewAnimation2: View {
    var body: some View {
        VStack {
            ZStack {
                VStack {
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 10, height: 20)
                    
                }
                HStack {
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                    Rectangle()
                        .fill(Color.white)
                        .frame(width: 20, height: 10)
                }
            }
        }
    }
}

#Preview {
    HelpViewAnimation2()
}
